### ISSUE TITLE
Seed Data For Tornado Shelters that are on readme in master

### ISSUE THREAD

**Issue by AustinMCrane** [openwichita/tornado-shelter-locator#6]

**Comment by AustinMCrane** [comment]
i need to create Shelter seed data for the shelters listed in README.md

**Comment by xRahul** [comment]
@AustinMCrane can you explain what is a seed data?

**Comment by AustinMCrane** [comment]
rails has a rake test you can run to "seed" your database (insert some data) with rake db:seed

this command looks in /db/seed.rb and runs the script
